$ANSIBLE_VAULT;1.1;AES256
31643833626331366566386438346530656336663132653033663336333065643332336236393035
3431373064663039313936643533326462393535383839640a343564626231343533353631373938
65303533333463616437333934613761643630663063386164636137656534383235336364653364
6535306365623934660a626134306136396664613839663933623965613062386533343364383730
3139
